#!/bin/bash
echo "Content-Type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html><head><title>Bash CGI Environment</title>"
echo "<style>body{font-family:monospace;padding:20px;background:#2c3e50;color:#ecf0f1;}"
echo ".env{background:#34495e;padding:10px;margin:5px 0;border-radius:3px;}</style>"
echo "</head><body>"
echo "<h1>Bash CGI Environment Variables</h1>"
echo "<div class='env'><strong>REQUEST_METHOD:</strong> $REQUEST_METHOD</div>"
echo "<div class='env'><strong>REQUEST_URI:</strong> $REQUEST_URI</div>"
echo "<div class='env'><strong>HTTP_HOST:</strong> $HTTP_HOST</div>"
echo "<div class='env'><strong>HTTP_USER_AGENT:</strong> $HTTP_USER_AGENT</div>"
echo "<div class='env'><strong>SERVER_NAME:</strong> $SERVER_NAME</div>"
echo "<div class='env'><strong>SERVER_PORT:</strong> $SERVER_PORT</div>"
echo "<div class='env'><strong>QUERY_STRING:</strong> $QUERY_STRING</div>"
echo "<div class='env'><strong>CONTENT_TYPE:</strong> $CONTENT_TYPE</div>"
echo "<div class='env'><strong>CONTENT_LENGTH:</strong> $CONTENT_LENGTH</div>"
echo "<h2>All Environment Variables:</h2>"
echo "<pre>"
env | sort
echo "</pre>"
echo "<a href='/' style='color:#3498db;'>← Back to Test Suite</a>"
echo "</body></html>"
